[profile.default]
src = "src"
out = "out"
libs = ["lib"]

rpc_endpoints= { sepolia = "https://eth-sepolia.g.alchemy.com/v2/2e1O9w1kAi2lhdaBprjL30ohl85aH2jM", arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/2e1O9w1kAi2lhdaBprjL30ohl85aH2jM" }



remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@ccip/=lib/ccip/",
    "@chainlink/local/=lib/chainlink-local/"


]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
